USE master
CREATE DATABASE BD_POLI_TRADUCCION
GO

USE BD_POLI_TRADUCCION
GO

CREATE TABLE TBL_USUARIOS(
  NOMBRE VARCHAR(50) UNIQUE,
  CONTRASENNA VARCHAR(50) NOT NULL,
  PRIMARY KEY (NOMBRE)
)

CREATE TABLE TBL_IDIOMAS(
  NOMBRE VARCHAR(50) UNIQUE,
  POPULARIDAD INT,
  PRIMARY KEY (NOMBRE)
)

CREATE TABLE TBL_FRASES(
  PALABRA VARCHAR(50) UNIQUE NOT NULL,
  POPULARIDAD INT,
  PRIMARY KEY (PALABRA)
)

CREATE TABLE TBL_FRASES_POR_IDIOMAS(
  PALABRA VARCHAR(50) UNIQUE,
  IDIOMA VARCHAR(50) NOT NULL,
  FRASE_ORIGEN VARCHAR(50) NOT NULL,
  PRIMARY KEY (PALABRA),
  FOREIGN KEY (IDIOMA) REFERENCES TBL_IDIOMAS(NOMBRE),
  FOREIGN KEY (FRASE_ORIGEN) REFERENCES TBL_FRASES(PALABRA)
)

CREATE TABLE TBL_TRADUCCIONES(
  ID_TRADUCCION INT NOT NULL IDENTITY(1,1),
  NOMBRE_USUARIO VARCHAR(50) NOT NULL,
  FECHA DATE NOT NULL,
  IDIOMA VARCHAR(50) NOT NULL,
  FRASE_ORIGEN VARCHAR(50) NOT NULL,
  FRASE_TRADUCIDA VARCHAR(50) NOT NULL,
  POPULARIDAD INT NOT NULL,
  PRIMARY KEY (ID_TRADUCCION),
  FOREIGN KEY (NOMBRE_USUARIO) REFERENCES TBL_USUARIOS(NOMBRE),
  FOREIGN KEY (IDIOMA) REFERENCES TBL_IDIOMAS(NOMBRE),
  FOREIGN KEY (FRASE_ORIGEN) REFERENCES TBL_FRASES(PALABRA),
  FOREIGN KEY (FRASE_TRADUCIDA) REFERENCES TBL_FRASES_POR_IDIOMAS(PALABRA)
)
GO
  --PROCEDIMIENTOS ALMACENADOS
  --USUARIOS
  CREATE PROCEDURE CRE_USUARIO_PR
	@P_NOMBRE VARCHAR(50),
	@P_CONTRASENNA VARCHAR(50)
AS BEGIN
INSERT INTO TBL_USUARIOS(
	NOMBRE,
	CONTRASENNA
)
VALUES (
	@P_NOMBRE,
	@P_CONTRASENNA
)
END 
GO

CREATE PROCEDURE RET_USUARIO_PR
	@P_NOMBRE VARCHAR(50)
AS BEGIN
SELECT * FROM TBL_USUARIOS
WHERE NOMBRE = @P_NOMBRE
END 
GO

CREATE PROCEDURE RET_USUARIO_BY_TRADUCCION_PR
AS BEGIN
SELECT TOP 1 TU.NOMBRE,TU.CONTRASENNA FROM TBL_TRADUCCIONES
INNER JOIN TBL_USUARIOS AS TU
ON  TBL_TRADUCCIONES.NOMBRE_USUARIO = TU.NOMBRE
GROUP BY TU.NOMBRE,TU.CONTRASENNA
ORDER BY COUNT(*) DESC
END 
GO
--IDIOMA
CREATE PROCEDURE CRE_IDIOMA_PR
	@P_NOMBRE VARCHAR(50)
AS BEGIN
	DECLARE @POPULARIDAD INT
    SET @POPULARIDAD = 0
INSERT INTO TBL_IDIOMAS(
	NOMBRE,
	POPULARIDAD
)
VALUES (
	@P_NOMBRE,
	@POPULARIDAD
)
END 
GO

CREATE PROCEDURE RET_IDIOMA_PR
	@P_NOMBRE VARCHAR(50)
AS BEGIN
SELECT * FROM TBL_IDIOMAS
WHERE NOMBRE = @P_NOMBRE
END 
GO

CREATE PROCEDURE RET_IDIOMA_MOST_POPULAR_PR
AS BEGIN
SELECT TOP 1 * FROM TBL_IDIOMAS
ORDER BY POPULARIDAD DESC
END 
GO


CREATE PROCEDURE RET_ALL_IDIOMA_PR
AS BEGIN
SELECT * FROM TBL_IDIOMAS
END 
GO

--FRASE
CREATE PROCEDURE CRE_FRASE_PR
	@P_PALABRA VARCHAR(50)
AS BEGIN
	DECLARE @POPULARIDAD INT
    SET @POPULARIDAD = 0
INSERT INTO TBL_FRASES(
	PALABRA,
	POPULARIDAD
)
VALUES (
	@P_PALABRA,
	@POPULARIDAD
)
END 
GO

CREATE PROCEDURE RET_FRASE_PR
	@P_PALABRA VARCHAR(50)
AS BEGIN
SELECT * FROM TBL_FRASES
WHERE PALABRA = @P_PALABRA
END 
GO

CREATE PROCEDURE ADD_FRASE_POPULARIDAD_PR
	@P_PALABRA VARCHAR(50)
AS BEGIN
    DECLARE @V_POPULARIDAD INT
    SET @V_POPULARIDAD =((SELECT SUM(TF.POPULARIDAD) FROM TBL_FRASES AS TF WHERE TF.PALABRA=@P_PALABRA)+1)
UPDATE TBL_FRASES
SET POPULARIDAD = @V_POPULARIDAD
WHERE PALABRA = @P_PALABRA
END 
GO

CREATE PROCEDURE RET_ALL_FRASE_PR
AS BEGIN
SELECT * FROM TBL_FRASES
END 
GO

CREATE PROCEDURE RET_ALL_FRASE_BY_POPULARITY_PR
AS BEGIN
SELECT TOP 100 * FROM TBL_FRASES
ORDER BY POPULARIDAD ASC
END 
GO
--FRASE_TRADUCIDA
CREATE PROCEDURE CRE_FRASE_TRADUCIDA_PR
	@P_PALABRA VARCHAR(50),
	@P_IDIOMA VARCHAR(50),
	@P_FRASE_ORIGEN VARCHAR(50)
AS BEGIN
INSERT INTO TBL_FRASES_POR_IDIOMAS(
	PALABRA,
	IDIOMA,
	FRASE_ORIGEN
)
VALUES (
	@P_PALABRA,
	@P_IDIOMA,
	@P_FRASE_ORIGEN
)
END 
GO

CREATE PROCEDURE RET_ALL_FRASE_TRADUCIDA_BY_IDIOMA_PR
	@P_IDIOMA VARCHAR(50)
AS BEGIN
SELECT * FROM TBL_FRASES_POR_IDIOMAS
WHERE IDIOMA = @P_IDIOMA
END 
GO

CREATE PROCEDURE RET_ALL_FRASE_TRADUCIDA_BY_PALABRA_PR
	@P_FRASE_ORIGEN VARCHAR(50)
AS BEGIN
SELECT * FROM TBL_FRASES_POR_IDIOMAS
WHERE FRASE_ORIGEN = @P_FRASE_ORIGEN
END 
GO

CREATE PROCEDURE RET_FRASE_TRADUCIDA_PR
	@P_FRASE_ORIGEN VARCHAR(50),
	@P_IDIOMA VARCHAR(50)
AS BEGIN
SELECT * FROM TBL_FRASES_POR_IDIOMAS
WHERE FRASE_ORIGEN = @P_FRASE_ORIGEN
AND IDIOMA = @P_IDIOMA
END 
GO

CREATE PROCEDURE RET_ALL_FRASE_TRADUCIDA_PR
AS BEGIN
SELECT * FROM TBL_FRASES_POR_IDIOMAS
END 
GO
--TRADUCCIONES
CREATE PROCEDURE CRE_TRADUCCION_PR
	@P_NOMBRE_USUARIO VARCHAR(50),
	@P_FECHA DATE,
	@P_IDIOMA VARCHAR(50),
	@P_FRASE_ORIGEN VARCHAR(50),
	@P_FRASE_TRADUCIDA VARCHAR(50),
	@P_POPULARIDAD INT
AS BEGIN
    DECLARE @V_POPULARIDAD_IDIOMA INT
    SET @V_POPULARIDAD_IDIOMA =((SELECT SUM(TI.POPULARIDAD) FROM TBL_IDIOMAS AS TI WHERE TI.NOMBRE=@P_IDIOMA)+1)
INSERT INTO TBL_TRADUCCIONES(
	NOMBRE_USUARIO,
	FECHA,
	IDIOMA,
	FRASE_ORIGEN,
	FRASE_TRADUCIDA,
	POPULARIDAD
)
VALUES (
	@P_NOMBRE_USUARIO,
	@P_FECHA,
	@P_IDIOMA,
	@P_FRASE_ORIGEN,
	@P_FRASE_TRADUCIDA,
	@P_POPULARIDAD
)
UPDATE TBL_IDIOMAS
SET POPULARIDAD = @V_POPULARIDAD_IDIOMA
WHERE NOMBRE = @P_IDIOMA
END 
GO

CREATE PROCEDURE RET_ALL_TRADUCCION_PR
AS BEGIN
SELECT * FROM TBL_TRADUCCIONES
END 
GO

CREATE PROCEDURE RET_ALL_TRADUCCION_BY_PALABRA_PR
	@P_FRASE_ORIGEN VARCHAR(50)
AS BEGIN
SELECT * FROM TBL_TRADUCCIONES
WHERE FRASE_ORIGEN LIKE CONCAT('%', @P_FRASE_ORIGEN, '%')
END 
GO